### ISSUE TITLE
No matching function error

### ISSUE THREAD

**Issue by weiguochow** [TAMS-Group/bio_ik_service#1]
Hello, the repo `bio_ik_service` is incompatible with moveit-kinetic, bio_ik-kinematic. Which is master branch of `bio_ik`? Thank you!

**Comment by dumyy** [comment]
This master should be Melodic -support. I have changed it to support moveit-kinetic in [https://github.com/dumyy/bio_ik_service/tree/kinetic-support](url)  and tested it well.
Hope that can help you. @weiguochow

**Comment by lianghongzhuo** [comment]
similar to https://github.com/TAMS-Group/bio_ik_service/issues/2
you can check out to the correct tag for kinect support:
```
git checkout kinetic-support
```
for bio_ik do the same command.
