### ISSUE TITLE
bio_ik_service

### ISSUE THREAD

**Issue by dumyy** [TAMS-Group/bio_ik_service#2]
could you please provide a ros-kinetic version? thank you.

**Comment by awesomebytes** [comment]
It would be appreciated, indeed.

As a note, checking out commit `30d4a888da3728e8c8c0d3300f7b7ee9fe8d888d` (before the last changes in 2019) will make it work on kinetic (with bio_ik set to the `kinetic-support` branch).

**Comment by v4hn** [comment]
Thanks for the update here @awesomebytes .
I just pushed a corresponding `kinetic-support` tag for this repository.

Please note that we do not maintain branches for individual ROS distributions.
Instead we simply tag the last working version. Apparently I missed to do it for this repository, which nobody in our group actively uses at the moment (as far as I know).

I consider the pushed tag to resolve this issue.

**Comment by awesomebytes** [comment]
@v4hn That's a great resolution, thanks :)
